language: php
php:
  - 7.2

before_script:
  - travis_retry composer self-update
  - travis_retry composer install

script:
  - php vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
